import { PT_Serif, DM_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/contexts/fetchData";


const pt = PT_Serif({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-serif",
})

const dm = DM_Mono({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  variable: "--font-mono",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const value = { name: "React" };
  return (
    <html lang="en" className={`${dm.variable} ${pt.variable}`}>
      <body
        className={` antialiased`}
      >
        <Provider value={value}>{children}</Provider>
      </body>
    </html>
  );
}
